In [13]:
import numpy as np

In [14]:
u = np.array([1,2,5,4,7])
u

array([1, 2, 5, 4, 7])

In [15]:
v = np.exp(u)   # 使用np中的操作能比for循环更有效率
v

array([   2.71828183,    7.3890561 ,  148.4131591 ,   54.59815003,
       1096.63315843])

In [16]:
v = np.log(u)   # 这样能比for循环效率更高
v

array([0.        , 0.69314718, 1.60943791, 1.38629436, 1.94591015])

In [17]:
maxs = np.max(u)  # 这样能比for循环效率更高
maxs

7

In [19]:
# 使用python中的广播功能
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [21]:
cal = A.sum(axis = 0)
# axis 参数 0表示按照列， 1表示按照行
cal

array([ 59. , 239. , 155.4,  76.9])

In [23]:
percentage = 100 * A / cal.reshape(1, 4)
# 实际上不需要reshape，reshape算法O(1) 效率很高 
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [31]:
 # numpy 中需要注意的一些事项
a = np.random.randn(5) # 这样做不好
a = np.random.randn(5, 1) # 声明两维数据更不容易出错误
assert(a.shape == (5, 1))  # 通过assert来检查矩阵形状是否正确