## 测验作业

In [ ]:
import numpy as np

In [6]:
# 3. img是一个(32,32,3)的数组，具有3个颜色通道：红色、绿色和蓝色的32x32像素图像。如何将其重新转换为列向量？
img = np.array(np.random.randn(32, 32, 3))
x = img.reshape((32 * 32 * 3, 1))
x

array([[ 1.05337833],
       [ 0.33835626],
       [ 0.52176529],
       ...,
       [ 0.91680584],
       [-1.3540557 ],
       [ 2.41274082]])

In [10]:
# 4. 请问以下代码的c数组是几维的？
a = np.random.randn(2, 3)
b = np.random.randn(2, 1)
c = a + b
c
# c 是一个2 * 3 维的数组，这里采用了广播的机制

array([[-1.36967232, -2.28472731, -0.96762693],
       [-1.61320935,  1.05671874,  0.33049141]])

In [19]:
# 5. 看下面两个随机数组相乘后维度是多少
a = np.random.randn(4, 3)
b = np.random.randn(3, 2)
c = a * b
c
# 这样的运算会报错，因为*运算符需要两个矩阵之间的维度形同，按匀速乘法来相乘

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [21]:
# 7. 回想 np.dot(a, b)在 a和b上执行矩阵乘法，而 a*b执行元素方式的乘法。
a = np.random.randn(12288, 150)
b = np.random.randn(150, 45)
c = np.dot(a, b)
c
#  此时的c是12288x45维度的

array([[-26.60532195, -26.03396775, -14.49426498, ...,  -5.17209173,
        -13.18009455,   1.45071806],
       [ -4.24444292,  14.11690076, -31.5034917 , ...,  16.52925407,
        -31.31089193,  -1.97023362],
       [-24.87278328,   7.84532877, -21.46309759, ...,  14.82404402,
         -1.06258898,   9.05840717],
       ...,
       [ -4.2381351 ,  13.01532785,  12.58888674, ...,   3.40292301,
          7.69888344,   5.64503843],
       [  6.74792981,  11.22744947,   1.12223578, ...,  18.08046355,
         -6.1302688 ,  10.75865451],
       [  5.52265492,  -5.77448813,   6.11803285, ...,  -9.77993977,
          1.54967679,   5.85098032]])

In [27]:
# 9. 看一下下面代码，结果c的维度是什么？
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a * b
c
# c 最终的维度为3x3，因为b通过广播变成3*3

[[ 0.53910854 -0.34269043 -0.99233688]
 [ 2.21727047  0.18530932 -0.81300455]
 [-0.6567717   0.82552466 -0.31779103]]
[[0.58319674]
 [0.16414653]
 [1.8267553 ]]


array([[ 0.31440634, -0.19985594, -0.57872763],
       [ 0.36395725,  0.03041788, -0.13345188],
       [-1.19976118,  1.50803154, -0.58052646]])

## 编程作业

In [23]:
# 8. 看下面的代码如何将该片段向量化
a = np.random.randn(3, 4)
b = np.random.randn(4, 1)

# for i in range(3):
#     for j in range(4):
#         c[i][j] = a[i][j] + b[i]

# Answer:
c = a + b.T
c

array([[-1.35049094,  1.6470698 , -0.27387021,  2.88956639],
       [-1.12681352,  0.76864298, -2.07599686,  2.54007515],
       [ 0.59512988,  1.42651949, -1.06419343,  2.13373075]])